server:
  port: 8888

logging.file: backend-api.log

spring:
  profiles: default
  datasource:
    username: demo
    password: demo
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/demo?autoReconnect=true&useUnicode=true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 3600000
    validationQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate.show_sql: true
  velocity:
    resource-loader-path:classpath:/mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: test@gmail.com
    password: test
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
